on:
  push:

jobs:
  build:
    runs-on: 'ubuntu-24.04'
    environment: default_env
    env:
      PRUSASLICER_VERSION: '2.9.4'
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      # Just so we can cache stuff
      - name: Install buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      # Use bake since it can read a docker-compose.yml
      - name: Build and push
        uses: docker/bake-action@v6
        with:
          source: "{{defaultContext}}:docker/"
          load: true
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
            prusaslicer-base.args.PRUSASLICER_TAG=version_${{ env.PRUSASLICER_VERSION }}
            *.tags=julianneswinoga/prusaslicer-web:${{ env.PRUSASLICER_VERSION }}
