on:
  push:

jobs:
  build:
    runs-on: 'ubuntu-24.04'
    environment: default_env
    steps:
      - uses: actions/checkout@v5
      - name: Set TAG_NAME
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "TAG_NAME=${{ github.ref_name }}" | tee -a $GITHUB_ENV

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Read compose PRUSASLICER_TAG
        run: |
          cd docker/
          compose_prusaslicer_tag=$(docker compose config --format=json | jq -r '.services."prusaslicer-base".build.args.PRUSASLICER_TAG')
          compose_prusaslicer_version=$(echo "$compose_prusaslicer_tag" | sed 's/^version_//')
          echo "compose_prusaslicer_version=$compose_prusaslicer_version" | tee -a $GITHUB_ENV

      - name: Get latest upstream release tag
        run: |
          latest_upstream_tag=$(curl --show-error --silent --location https://api.github.com/repos/prusa3d/PrusaSlicer/releases/latest | jq -r '.tag_name')
          latest_upstream_version=$(echo "$latest_upstream_tag" | sed 's/^version_//')
          echo "latest_upstream_version=$latest_upstream_version" | tee -a $GITHUB_ENV

      - name: Log in to Docker Hub
        if: ${{ env.TAG_NAME != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      # Just so we can cache stuff
      - name: Expose GitHub Runtime  # https://github.com/docker/bake-action/issues/36 ?
        uses: crazy-max/ghaction-github-runtime@v3
      - name: Install buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      # Use bake since it can read a docker-compose.yml
      - name: Build and maybe push
        uses: docker/bake-action@v6
        with:
          source: "{{defaultContext}}:docker/"
          load: true
          push: ${{ env.TAG_NAME != '' }}
          # https://old.reddit.com/r/devops/comments/1ejb7ed/github_actions_doesnt_seem_to_be_using_docker/lgfskeu/
          set: |
            *.cache-from=type=gha,version=2,url_v2=${{ env.ACTIONS_RESULTS_URL }},token=${{ env.ACTIONS_RUNTIME_TOKEN }},ACTIONS_RUNTIME_TOKEN=${{ secrets.GITHUB_TOKEN }}
            *.cache-to=type=gha,mode=max,version=2,url_v2=${{ env.ACTIONS_RESULTS_URL }},token=${{ env.ACTIONS_RUNTIME_TOKEN }},ACTIONS_RUNTIME_TOKEN=${{ secrets.GITHUB_TOKEN }}
            
            prusaslicer-base.args.PRUSASLICER_TAG=version_${{ env.compose_prusaslicer_version }}
            *.tags=julianneswinoga/prusaslicer-web:latest
            *.tags=julianneswinoga/prusaslicer-web:${{ env.compose_prusaslicer_version }}
            *.tags=julianneswinoga/prusaslicer-web:${{ env.TAG_NAME }}-${{ env.compose_prusaslicer_version }}

      - name: Update Docker Hub Description
        if: ${{ env.TAG_NAME != '' }}
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
          repository: julianneswinoga/prusaslicer-web
          short-description: 'https://github.com/julianneswinoga/prusaslicer-web'
          enable-url-completion: true
