name: build-and-release
on:
  push:
    tags:
      - '*'
    branches-ignore:
      - 'autoupdate/*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-release:
    runs-on: 'ubuntu-latest'
    environment: default_env
    steps:
      - uses: actions/checkout@v5
      - name: Set git_tag_name
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "git_tag_name=${{ github.ref_name }}" | tee -a $GITHUB_ENV
      - name: Set docker_hub_tag_prefix
        run: |
          if [ -n "$git_tag_name" ]; then
            echo "docker_hub_tag_prefix=$git_tag_name" | tee -a $GITHUB_ENV
          else
            full_sha=${{ github.sha }}
            # Trim to 8
            echo "docker_hub_tag_prefix=${full_sha::8}" | tee -a $GITHUB_ENV
          fi

      - name: Read hcl PRUSASLICER_TAG
        run: |
          cd docker/
          hcl_prusaslicer_tag=$(docker buildx bake --print | jq -r '.target."prusaslicer-base".args.PRUSASLICER_TAG')
          hcl_prusaslicer_version=$(echo "$hcl_prusaslicer_tag" | sed 's/^version_//')
          echo "hcl_prusaslicer_version=$hcl_prusaslicer_version" | tee -a $GITHUB_ENV

      - name: Log in to Docker Hub
        if: ${{ env.git_tag_name != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      # Just so we can cache stuff
      - name: Expose GitHub Runtime  # https://github.com/docker/bake-action/issues/36 ?
        uses: crazy-max/ghaction-github-runtime@v3
      - name: Install buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build and maybe push
        uses: docker/bake-action@v6
        with:
          source: "{{defaultContext}}:docker/"
          load: true
          push: ${{ env.git_tag_name != '' }}
          # https://old.reddit.com/r/devops/comments/1ejb7ed/github_actions_doesnt_seem_to_be_using_docker/lgfskeu/
          set: |
            *.cache-from=type=gha,version=2,url_v2=${{ env.ACTIONS_RESULTS_URL }},token=${{ env.ACTIONS_RUNTIME_TOKEN }},ACTIONS_RUNTIME_TOKEN=${{ secrets.GITHUB_TOKEN }}
            *.cache-to=type=gha,mode=max,version=2,url_v2=${{ env.ACTIONS_RESULTS_URL }},token=${{ env.ACTIONS_RUNTIME_TOKEN }},ACTIONS_RUNTIME_TOKEN=${{ secrets.GITHUB_TOKEN }}
            
            prusaslicer-base.args.PRUSASLICER_TAG=version_${{ env.hcl_prusaslicer_version }}
            *.tags=julianneswinoga/prusaslicer-web:latest
            *.tags=julianneswinoga/prusaslicer-web:${{ env.hcl_prusaslicer_version }}
            *.tags=julianneswinoga/prusaslicer-web:${{ env.docker_hub_tag_prefix }}-${{ env.hcl_prusaslicer_version }}

      - name: Update Docker Hub Description
        if: ${{ env.git_tag_name != '' }}
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
          repository: julianneswinoga/prusaslicer-web
          short-description: 'https://github.com/julianneswinoga/prusaslicer-web'
          enable-url-completion: true
