name: pr-from-upstream-release
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'  # Every day at 04:00

jobs:
  check-upstream-release:
    runs-on: 'ubuntu-latest'
    environment: julie_bot_env
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v5

      - name: Read hcl PRUSASLICER_TAG
        run: |
          cd docker/
          hcl_prusaslicer_tag=$(docker buildx bake --print | jq -r '.target."prusaslicer-base".args.PRUSASLICER_TAG')
          hcl_prusaslicer_version=$(echo "$hcl_prusaslicer_tag" | sed 's/^version_//')
          echo "hcl_prusaslicer_version=$hcl_prusaslicer_version" | tee -a $GITHUB_ENV

      - name: Get latest upstream release tag
        run: |
          latest_upstream_tag=$(curl --show-error --silent --location https://api.github.com/repos/prusa3d/PrusaSlicer/releases/latest | jq -r '.tag_name')
          latest_upstream_version=$(echo "$latest_upstream_tag" | sed 's/^version_//')
          echo "latest_upstream_version=$latest_upstream_version" | tee -a $GITHUB_ENV

      - name: Check if upstream has released a newer version
        run: |
          set -x
          if dpkg --compare-versions "$latest_upstream_version" 'gt' "$hcl_prusaslicer_version"; then
            echo 'upstream_has_newer_release=true' | tee -a $GITHUB_ENV
          else
            echo 'upstream_has_newer_release=false' | tee -a $GITHUB_ENV
          fi

      - name: Update source code
        if: ${{ env.upstream_has_newer_release == 'true' }}
        run: |
          perl -i -pe 's|\Q${{ env.latest_upstream_version }}\E|${{ env.hcl_prusaslicer_version }}|g' docker/docker-bake.hcl
          perl -i -pe 's|\Q${{ env.latest_upstream_version }}\E|${{ env.hcl_prusaslicer_version }}|g' docker/prusaslicer-base/Dockerfile

      - name: Create Pull Request
        if: ${{ env.upstream_has_newer_release == 'true' }}
        uses: peter-evans/create-pull-request@v7
        with:
          # Needed to fuss with bots for the PR to trigger the normal workflows:
          # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: |
            Automatic update from ${{ env.hcl_prusaslicer_version }} to ${{ env.latest_upstream_version }}
          branch: |
            autoupdate/${{ env.latest_upstream_version }}
          title: |
            Automatic update from ${{ env.hcl_prusaslicer_version }} to ${{ env.latest_upstream_version }}
          body: |
            Automatic update from ${{ env.hcl_prusaslicer_version }} to ${{ env.latest_upstream_version }}
